export const SIGN_IN_UPDATE_NAME = "SIGN_IN_UPDATE_NAME";
export const SIGN_IN_UPDATE_PASSWORD = "SIGN_IN_UPDATE_PASSWORD";
export const SIGN_IN_LOADING = "SIGN_IN_LOADING";
export const SIGN_IN_STOP_LOADING = "SIGN_IN_STOP_LOADING";
export const SIGN_IN_RESET = "SIGN_IN_RESET";

export const SIGN_UP_UPDATE_NAME = "SIGN_UP_UPDATE_NAME";
export const SIGN_UP_UPDATE_EMAIL = "SIGN_UP_UPDATE_EMAIL";
export const SIGN_UP_UPDATE_PASSWORD = "SIGN_UP_UPDATE_PASSWORD";
export const SIGN_UP_UPDATE_PHONE = "SIGN_UP_UPDATE_PHONE";
export const SIGN_UP_UPDATE_MONTH = "SIGN_UP_UPDATE_MONTH";
export const SIGN_UP_UPDATE_YEAR = "SIGN_UP_UPDATE_YEAR";
export const SIGN_UP_UPDATE_DAY = "SIGN_UP_UPDATE_DAY";
export const SIGN_UP_UPDATE_COUNTRY = "SIGN_UP_UPDATE_COUNTRY";
export const SIGN_UP_UPDATE_CITY = "SIGN_UP_UPDATE_CITY";
export const SIGN_UP_UPDATE_IMAGES = "SIGN_UP_UPDATE_IMAGES";
export const SIGN_UP_SET_MONTHS = "SIGN_UP_SET_MONTHS";
export const SIGN_UP_SET_YEARS = "SIGN_UP_SET_YEARS";
export const SIGN_UP_SET_DAYS = "SIGN_UP_SET_DAYS";
export const SIGN_UP_SET_COUNTRIES = "SIGN_UP_SET_COUNTRIES";
export const SIGN_UP_SET_CITES = "SIGN_UP_SET_CITES";
export const SIGN_UP_RESET = "SIGN_UP_RESET";
export const SIGN_UP_LOADING = "SIGN_UP_LOADING";
export const SIGN_UP_STOP_LOADING = "SIGN_UP_STOP_LOADING";

export const CALENDAR_SET_MARKED_DAYS = "CALENDAR_SET_MARKED_DAYS";
export const CALENDAR_LOADING = "CALENDAR_LOADING";
export const CALENDAR_STOP_LOADING = "CALENDAR_STOP_LOADING";
export const CALENDAR_RESET = "CALENDAR_RESET";

export const AUDITION_LOADING = "AUDITION_LOADING";
export const AUDITION_STOP_LOADING = "AUDITION_STOP_LOADING";
export const AUDITION_GET_AUDITIONS = "AUDITION_GET_AUDITIONS";
export const AUDITION_DETAILS_LOADING = "AUDITION_DETAILS_LOADING";
export const AUDITION_DETAILS_STOP_LOADING = "AUDITION_DETAILS_STOP_LOADING";
export const AUDITION_DETAILS_GET_ITEM = "AUDITION_DETAILS_GET_ITEM";
export const AUDITION_DETAILS_LOADING_POPUP = "AUDITION_DETAILS_LOADING_POPUP";

export const HALL_OF_FAME_LOADING = "HALL_OF_FAME_LOADING";
export const HALL_OF_FAME_STOP_LOADING = "HALL_OF_FAME_STOP_LOADING";
export const HALL_OF_FAME_GET_ITEMS = "HALL_OF_FAME_GET_ITEMS";
export const HALL_OF_FAME_GET_CATEGORIES = "HALL_OF_FAME_GET_CATEGORIES";
export const HALL_OF_FAME_SET_CATEGORIES = "HALL_OF_FAME_SET_CATEGORIES";
export const HALL_OF_FAME_CATEGORIES_LOADING = "HALL_OF_FAME_CATEGORIES_LOADING";
export const HALL_OF_FAME_CATEGORIES_STOP_LOADING = "HALL_OF_FAME_CATEGORIES_STOP_LOADING";
export const HALL_OF_FAME_RESET = "HALL_OF_FAME_RESET";
export const HALL_OF_FAME_TOGGLE_SEARCH = "HALL_OF_FAME_TOGGLE_SEARCH";
export const HALL_OF_FAME_SEARCH_LOADING = "HALL_OF_FAME_SEARCH_LOADING";
export const HALL_OF_FAME_SEARCH_STOP_LOADING = "HALL_OF_FAME_SEARCH_STOP_LOADING";
export const HALL_OF_FAME_SEARCH_SET_ITEMS = "HALL_OF_FAME_SEARCH_SET_ITEMS";
export const HALL_OF_FAME_RESET_SEARCH = "HALL_OF_FAME_RESET_SEARCH";

export const FORGET_PASSWORD_UPDATE_MAIL = "FORGET_PASSWORD_UPDATE_MAIL";
export const FORGET_PASSWORD_LOADING = "FORGET_PASSWORD_LOADING";
export const FORGET_PASSWORD_STOP_LOADING = "FORGET_PASSWORD_STOP_LOADING";
export const FORGET_PASSWORD_RESET = "FORGET_PASSWORD_RESET";

export const PROFILE_GET_INFO = "PROFILE_GET_INFO";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_STOP_LOADING = "PROFILE_STOP_LOADING";

export const CONTACT_US_LOADING = "CONTACT_US_LOADING";
export const CONTACT_US_STOP_LOADING = "CONTACT_US_STOP_LOADING";
export const CONTACT_US_GET_ITEMS = "CONTACT_US_GET_ITEMS";

export const INFO_LOADING = "INFO_LOADING";
export const INFO_STOP_LOADING = "INFO_STOP_LOADING";
export const INFO_GET_PACKAGES = "INFO_GET_PACKAGES";
export const INFO_SET_USER = "INFO_SET_USER";
export const INFO_SUBSCRIBE_LOADING = "INFO_SUBSCRIBE_LOADING";
export const INFO_SUBSCRIBE_STOP_LOADING = "INFO_SUBSCRIBE_STOP_LOADING";

export const VERIFY_CODE_UPDATE_1 = "VERIFY_CODE_UPDATE_1";
export const VERIFY_CODE_UPDATE_2 = "VERIFY_CODE_UPDATE_2";
export const VERIFY_CODE_UPDATE_3 = "VERIFY_CODE_UPDATE_3";
export const VERIFY_CODE_UPDATE_4 = "VERIFY_CODE_UPDATE_4";
export const VERIFY_CODE_UPDATE_5 = "VERIFY_CODE_UPDATE_5";
export const VERIFY_CODE_LOADING = "VERIFY_CODE_LOADING";
export const VERIFY_CODE_STOP_LOADING = "VERIFY_CODE_STOP_LOADING";
export const VERIFY_CODE_RESET = "VERIFY_CODE_RESET";

export const RESET_PASSWORD_UPDATE_PASSWORD = "RESET_PASSWORD_UPDATE_PASSWORD";
export const RESET_PASSWORD_UPDATE_PASSWORD_AGAIN = "RESET_PASSWORD_UPDATE_PASSWORD_AGAIN";
export const RESET_PASSWORD_LOADING = "RESET_PASSWORD_LOADING";
export const RESET_PASSWORD_STOP_LOADING = "RESET_PASSWORD_STOP_LOADING";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";

export const PORTFOLIO_LOADING = "PORTFOLIO_LOADING";
export const PORTFOLIO_STOP_LOADING = "PORTFOLIO_STOP_LOADING";
export const PORTFOLIO_SECTION_LOADING = "PORTFOLIO_SECTION_LOADING";
export const PORTFOLIO_SECTION_STOP_LOADING = "PORTFOLIO_SECTION_STOP_LOADING";
export const PORTFOLIO_GET_ABOUT = "PORTFOLIO_GET_ABOUT";
export const PORTFOLIO_GET_EDUCATION = "PORTFOLIO_GET_EDUCATION";
export const PORTFOLIO_GET_TALENTS = "PORTFOLIO_GET_TALENTS";
export const PORTFOLIO_GET_EXPERIENCE = "PORTFOLIO_GET_EXPERIENCE";
export const PORTFOLIO_GET_TRAINING = "PORTFOLIO_GET_TRAINING";
export const PORTFOLIO_GET_PHOTO = "PORTFOLIO_GET_PHOTO";
export const PORTFOLIO_GET_VIDEO = "PORTFOLIO_GET_VIDEO";
export const PORTFOLIO_GET_POSTS = "PORTFOLIO_GET_POSTS";
export const PORTFOLIO_EDIT_BIO = "PORTFOLIO_EDIT_BIO";
export const PORTFOLIO_SET_USER_INFO = "PORTFOLIO_SET_USER_INFO";
export const PORTFOLIO_GET_FOLLOWERS = "PORTFOLIO_GET_FOLLOWERS";
export const PORTFOLIO_GET_COVER = "PORTFOLIO_GET_COVER";
export const PORTFOLIO_GET_PROFILE_PIC = "PORTFOLIO_GET_PROFILE_PIC";
export const PORTFOLIO_GET_ID = "PORTFOLIO_GET_ID";
export const PORTFOLIO_IS_IT_ME = "PORTFOLIO_IS_IT_ME";
export const PORTFOLIO_IS_FOLLOWING = "PORTFOLIO_IS_FOLLOWING";
export const PORTFOLIO_RESET = "PORTFOLIO_RESET";

export const HOME_GET_ITEMS = "HOME_GET_ITEMS";
export const HOME_LOADING = "HOME_LOADING";
export const HOME_CATEGORY_LOADING = "HOME_CATEGORY_LOADING";
export const HOME_STOP_LOADING = "HOME_STOP_LOADING";
export const HOME_CATEGORY_STOP_LOADING = "HOME_CATEGORY_STOP_LOADING";
export const HOME_SET_CATEGORIES = "HOME_SET_CATEGORIES";
export const HOME_SET_MIAN_TABS = "HOME_SET_MIAN_TABS";

export const ADD_POSTS_UPDATE_PHOTO = "ADD_POSTS_UPDATE_PHOTO";
export const ADD_POSTS_UPDATE_VIDEO = "ADD_POSTS_UPDATE_VIDEO";
export const ADD_POSTS_UPDATE_CAPTION = "ADD_POSTS_UPDATE_CAPTION";
export const ADD_POSTS_LOADING = "ADD_POSTS_LOADING";
export const ADD_POSTS_STOP_LOADING = "ADD_POSTS_STOP_LOADING";
export const ADD_POSTS_RESET = "ADD_POSTS_RESET";
export const ADD_POSTS_SET_STATUS = "ADD_POSTS_SET_STATUS";

export const POST_DETAILS_LOADING = "POST_DETAILS_LOADING";
export const POST_DETAILS_STOP_LOADING = "POST_DETAILS_STOP_LOADING";
export const POST_DETAILS_SET_ITEM = "POST_DETAILS_SET_ITEM";
export const POST_DETAILS_RESET = "POST_DETAILS_RESET";
export const POST_DETAILS_EDIT = "POST_DETAILS_EDIT";
export const POST_DETAILS_UPADTE_CAPTION = "POST_DETAILS_UPADTE_CAPTION";

export const ADD_INFO_LOADING = "ADD_INFO_LOADING";
export const ADD_INFO_STOP_LOADING = "ADD_INFO_STOP_LOADING";
export const ADD_INFO_ADD_ITEM_TO_EDUCATION = "ADD_INFO_ADD_ITEM_TO_EDUCATION";
export const ADD_INFO_ADD_ITEM_TO_EXPERIENCE = "ADD_INFO_ADD_ITEM_TO_EXPERIENCE";
export const ADD_INFO_ADD_ITEM_TO_TALENT = "ADD_INFO_ADD_ITEM_TO_TALENT";
export const ADD_INFO_ADD_ITEM_TO_TRAINING = "ADD_INFO_ADD_ITEM_TO_TRAINING";
export const ADD_INFO_SET_EDUCATION_VALUES = "ADD_INFO_SET_EDUCATION_VALUES";
export const ADD_INFO_SET_EXPERIENCES_VALUES = "ADD_INFO_SET_EXPERIENCES_VALUES";
export const ADD_INFO_SET_TALENTS_VALUES = "ADD_INFO_SET_TALENTS_VALUES";
export const ADD_INFO_SET_TRAINING_VALUES = "ADD_INFO_SET_TRAINING_VALUES";
export const ADD_INFO_TOGGLE_PICKER = "ADD_INFO_TOGGLE_PICKER";

export const NOTIFICATION_GET_ITEMS = "NOTIFICATION_GET_ITEMS";
export const NOTIFICATION_LOADING = "NOTIFICATION_LOADING";
export const NOTIFICATION_STOP_LOADING = "NOTIFICATION_STOP_LOADING";